- name: Create Floating IP Resource
  ansible.builtin.shell: |
    pcs resource create ClusterIP ocf:heartbeat:IPaddr2       ip={{ floating_ip }}       cidr_netmask={{ netmask }}       nic={{ cluster_iface }}       op monitor interval=30s
  notify: Restart pacemaker
